# Generated by Django 5.2.17 on 2026-09-28 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en_in', 'Indian English'), ('hinglish', 'Hinglish')], default='hinglish', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('dograh_workflow_uuid', models.CharField(blank=True, max_length=64)),
                ('dograh_trigger_uuid', models.CharField(blank=True, max_length=64)),
                ('tts_provider', models.CharField(blank=True, choices=[('', 'Organisation default'), ('sarvam', 'Sarvam Bulbul'), ('rumik', 'Rumik'), ('cartesia', 'Cartesia'), ('elevenlabs', 'ElevenLabs')], default='', max_length=32)),
                ('tts_voice', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.CharField(default='Priya', max_length=80)),
                ('goal', models.TextField(blank=True)),
                ('offer_details', models.TextField(blank=True)),
                ('prices', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('allowed_topics', models.JSONField(blank=True, default=list)),
                ('forbidden_topics', models.JSONField(blank=True, default=list)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('handoff_message', models.TextField(default="I don't have that information. A teammate will message you on WhatsApp or call you back.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundTemplateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_message_id', models.CharField(max_length=255, unique=True)),
                ('phone_e164', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
