# Generated by Django 5.2.17 on 2026-09-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.organisation'),
        ),
        migrations.AddField(
            model_name='campaigncontext',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignkeyword',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='outboundtemplatemessage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='campaigns.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignkeyword',
            unique_together={('campaign', 'keyword')},
        ),
    ]
