# Generated by Django 5.2.17 on 2026-09-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='permission_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
