# Generated by Django 5.2.17 on 2026-09-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_message_id', models.CharField(max_length=255, unique=True)),
                ('phone_raw', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField(blank=True)),
                ('raw', models.JSONField(default=dict)),
                ('matched_campaign_id', models.UUIDField(blank=True, null=True)),
                ('processing_status', models.CharField(default='received', max_length=32)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_messages', to='tenants.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
