# Generated by Django 5.2.17 on 2026-09-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_campaign_permission_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, default='customer advisor', max_length=120)),
                ('persona', models.TextField(blank=True)),
                ('greeting', models.TextField(blank=True, default='Hello, this is a call about the message you replied to.')),
                ('closing_line', models.TextField(blank=True, default='Thank you for your time. Goodbye.')),
                ('allow_interrupt', models.BooleanField(default=True)),
                ('max_call_seconds', models.PositiveIntegerField(default=300)),
                ('dograh_workflow_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dograh_workflow_uuid', models.CharField(blank=True, max_length=64)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_error', models.TextField(blank=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='campaigns.campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
