[transport-whatsapp]
type = transport
protocol = tls
bind = 0.0.0.0:5061
cert_file = /etc/asterisk/keys/sip.crt
priv_key_file = /etc/asterisk/keys/sip.key
method = tlsv1_2
external_media_address = ${SIP_HOSTNAME}
external_signaling_address = ${SIP_HOSTNAME}

#include pjsip_whatsapp.conf
