# Generated by Django 5.2.17 on 2026-09-28 11:51

import apps.common.fields
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenants.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.organisation')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deepgram_api_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('tts_provider', models.CharField(choices=[('sarvam', 'Sarvam Bulbul'), ('rumik', 'Rumik'), ('cartesia', 'Cartesia'), ('elevenlabs', 'ElevenLabs')], default='sarvam', max_length=32)),
                ('tts_voice', models.CharField(blank=True, default='anushka', max_length=80)),
                ('sarvam_api_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('rumik_api_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('cartesia_api_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('elevenlabs_api_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('dograh_api_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_keys', to='tenants.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelephonyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='vobiz', max_length=32)),
                ('did', models.CharField(blank=True, help_text='Indian caller ID, E.164, e.g. +911141234567', max_length=20)),
                ('dograh_from_phone_number_id', models.CharField(blank=True, help_text="Phone number id from Dograh's telephony config, sent as from_phone_number_id.", max_length=64)),
                ('telephony_configuration_id', models.CharField(blank=True, max_length=64)),
                ('auth_id', apps.common.fields.EncryptedTextField(blank=True)),
                ('auth_token', apps.common.fields.EncryptedTextField(blank=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephony', to='tenants.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waba_id', models.CharField(blank=True, max_length=64)),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('access_token', apps.common.fields.EncryptedTextField(blank=True)),
                ('app_secret', apps.common.fields.EncryptedTextField(blank=True)),
                ('verify_token', models.CharField(max_length=128)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp', to='tenants.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
