# Generated by Django 5.2.17 on 2026-09-29 04:58

import apps.common.fields
import apps.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.tenants.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppCalling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_number_e164', models.CharField(blank=True, max_length=20)),
                ('calling_enabled', models.BooleanField(default=False)),
                ('sip_enabled', models.BooleanField(default=False)),
                ('sip_password', apps.common.fields.EncryptedTextField(blank=True)),
                ('asterisk_endpoint', models.CharField(blank=True, max_length=40)),
                ('webhook_token', models.CharField(blank=True, max_length=80)),
                ('permission_message', models.CharField(default='May we call you on WhatsApp about the message you replied to?', max_length=500)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_calling', to='tenants.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TelephonyConnection',
        ),
    ]
