"""Render one PJSIP endpoint per business and ask Asterisk to reload it."""

import logging
import socket
from pathlib import Path

from django.conf import settings

logger = logging.getLogger(__name__)


def render_endpoint(calling):
    password = calling.sip_password or ""
    endpoint = calling.asterisk_endpoint
    number = (calling.business_number_e164 or "").lstrip("+")
    host = settings.SIP_HOSTNAME
    return f"""[{endpoint}]
type=endpoint
transport=transport-whatsapp
context=from-whatsapp
disallow=all
allow=opus,ulaw
webrtc=yes
direct_media=no
from_user={number}
from_domain={host}
aors={endpoint}
outbound_auth={endpoint}

[{endpoint}]
type=aor
contact=sip:wa.meta.vc:5061\\;transport=tls

[{endpoint}]
type=auth
auth_type=userpass
username={number}
password={password}
"""


def write_endpoints(calling_rows):
    directory = settings.ASTERISK_CONFIG_DIR
    if not directory:
        logger.info("ASTERISK_CONFIG_DIR is unset; skipping PJSIP render")
        return None
    body = "; generated by Caller. Do not edit.\n"
    for calling in calling_rows:
        if calling.sip_password and calling.asterisk_endpoint:
            body += render_endpoint(calling) + "\n"
    path = Path(directory) / "pjsip_whatsapp.conf"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)
    reload_pjsip()
    return path


def reload_pjsip():
    host = settings.ASTERISK_AMI_HOST
    secret = settings.ASTERISK_AMI_SECRET
    if not host or not secret:
        return
    username = settings.ASTERISK_AMI_USER
    payload = (
        f"Action: Login\r\nUsername: {username}\r\nSecret: {secret}\r\n\r\n"
        "Action: Command\r\nCommand: pjsip reload\r\n\r\n"
        "Action: Logoff\r\n\r\n"
    )
    try:
        with socket.create_connection((host, settings.ASTERISK_AMI_PORT), timeout=3) as sock:
            sock.sendall(payload.encode())
            sock.recv(1024)
    except OSError:
        logger.exception("Asterisk AMI reload failed")
