# Generated by Django 5.2.17 on 2026-09-28 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dograh_run_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(default='dialing', max_length=32)),
                ('transcript', models.TextField(blank=True)),
                ('recording_url', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_window', 'Waiting for calling window'), ('queued', 'Queued'), ('dialing', 'Dialing'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=32)),
                ('skip_reason', models.CharField(blank=True, max_length=80)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=64)),
                ('is_test', models.BooleanField(default=False)),
                ('source_message_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.TextField()),
                ('reason', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('wa_message_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
