# Generated by Django 5.2.17 on 2026-09-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0002_initial'),
        ('campaigns', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='tenants.organisation'),
        ),
        migrations.AddField(
            model_name='callattempt',
            name='call_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='calls.callrequest'),
        ),
        migrations.AddField(
            model_name='contextviolation',
            name='call_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='calls.callrequest'),
        ),
        migrations.AddField(
            model_name='contextviolation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='contextviolation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='tenants.organisation'),
        ),
        migrations.AddField(
            model_name='handoffalert',
            name='call_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_alerts', to='calls.callrequest'),
        ),
        migrations.AddField(
            model_name='handoffalert',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_alerts', to='tenants.organisation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='tenants.organisation'),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_requests', to='calls.lead'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('organisation', 'phone_e164')},
        ),
    ]
