# Generated by Django 5.2.17 on 2026-09-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrequest',
            name='status',
            field=models.CharField(choices=[('awaiting_permission', 'Awaiting WhatsApp permission'), ('permission_rejected', 'Permission rejected'), ('permission_expired', 'Permission expired'), ('pending_window', 'Waiting for calling window'), ('queued', 'Queued'), ('dialing', 'Dialing'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=32),
        ),
    ]
