# Generated by Django 5.2.17 on 2026-09-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=20)),
                ('reason', models.CharField(default='whatsapp_stop', max_length=80)),
            ],
        ),
    ]
