# Generated by Django 5.2.17 on 2026-09-28 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optout',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='tenants.organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='optout',
            unique_together={('organisation', 'phone_e164')},
        ),
    ]
