# Generated by Django 5.2.17 on 2026-09-29 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_initial'),
        ('tenants', '0002_alter_user_managers_whatsappcalling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_e164', models.CharField(max_length=20)),
                ('is_permanent', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_permissions', to='tenants.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
